#  db              88888888ba        ad888888b,     ,a8888a,     ad888888b,      88
#  d88b             88      "8b      d8"     "88   ,8P"'  `"Y8,  d8"     "88    ,d88
#  d8'`8b            88      ,8P              a8P  ,8P        Y8,         a8P  888888
#  d8'  `8b           88aaaaaa8P'           ,d8P"   88          88      ,d8P"       88
#  d8YaaaaY8b          88""""""'           a8P"      88          88    a8P"          88
#  d8""""""""8b         88                a8P'        `8b        d8'  a8P'            88
#  d8'        `8b   888  88  888          d8"           `8ba,  ,ad8'  d8"              88
#  d8'          `8b  888  88  888          88888888888     "Y8888P"    88888888888      88


# MagicalDreams - AnnualPassport Plugin - Main Config
# Copyright (C) 2012-2020 MagicalDreams.US - ALL RIGHTS RESERVED
# MagicalDreams Confidential - DO NOT SHARE